#!/bin/sh -e

echo "## Creating website container..."
toolbox create -c cockpit-website -r 35

run="toolbox run -c cockpit-website"

echo "## Installing RPM dependencies inside container..."
$run sudo dnf install -y rubygem-bundler \
	ruby-devel libffi-devel make gcc gcc-c++ redhat-rpm-config zlib-devel \
	libxml2-devel libxslt-devel tar nodejs \
	glibc-all-langpacks

echo "## Setting local gem path"
$run bundle config path .gem

echo "## Installing local gems"
$run bundle install

echo "## Done!"
echo "## Run _scripts/toolbox-jekyll"
